site_name: Knowledge Base
repo_url: https://github.com/minor-league-esports/knowledgeBase
theme:
  name: material
nav:
  - Home: index.md
  - Departments:
    - Rocket League Operations: departments/rocket-league-operations.md
    - Trackmania Operations: departments/trackmania-operations.md
    - Community: departments/community.md
    - Development:
      - Overview: departments/development.md
      - New Team Members: departments/new-team-members.md
      - Systems Overview: departments/systems-overview.md
        - Trackmania Operations KB: departments/trackmania-operations.md
        - Modmail KB: departments/modmail.md
    - Marketing: departments/marketing.md
    - Production: departments/production.md
